#!/bin/bash

while true
do
      # prepare for agent upgrade
      if [[ -f Macchiato_hd ]];then
            ./control stop
            sleep 1
            cp -f ops_agent ops_agent_old
            mv ops_agent_hd ops_agent
            sleep 1
            ./control start
            sleep 10
            pid=`cat var/app.pid`
		        if [[ -n $pid ]]; then
		            running=`ps -p $pid|grep -v "PID TTY" |wc -l`
		            if [[ $running -gt 0 ]]; then
				        rm -rf ops_agent_hd2
				    else
				    	  mv ops_agent ops_agent_hd2
				        cp -f ops_agent_old ops_agent
				        sleep 1
				        ./control start
				    fi
		        else
		        	  mv ops_agent ops_agent_hd2
			          cp -f ops_agent_old ops_agent
			          sleep 1
			          ./control start
		        fi
		  else
		        running=$(ps aux |grep ops_agent |grep -v grep |wc -l)
		        if [[ $running -eq 0 ]]; then
		            ./control start
		        fi
      fi
      sleep 10
done